"""add case risk_incomplete

Revision ID: 010bdda54467
Revises: 72321357df46
Create Date: 2026-09-23 01:28:26.886747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010bdda54467'
down_revision = '72321357df46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('risk_incomplete', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'risk_incomplete')
    # ### end Alembic commands ###
