"""add case risk

Revision ID: 72321357df46
Revises: b86e32e1cf77
Create Date: 2026-09-19 23:06:23.085804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72321357df46'
down_revision = 'b86e32e1cf77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('risk', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'risk')
    # ### end Alembic commands ###
